apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
  namespace: k8s
spec:
  selector:
    matchLabels:
      app: k8s-deployment
  template:
    metadata:
      labels:
        app: k8s-deployment
    spec:
      containers:
      - name: k8s-deployment
        image: openfile/k8s:0.0.2
        envFrom:
          - configMapRef:
              name: k8s-config
          - secretRef:
              name: k8s-secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
